name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Prepare and deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npm run lint
          npm run ng -- deploy --base-href=/little-inferno/ --name=${{ secrets.DISPLAY_NAME }} --email=${{ secrets.EMAIL }}
